### ISSUE TITLE
Add support for "remix" category

### ISSUE THREAD

**Issue by cellularmitosis** [delight-im/MovieContentFilter#1]
It might be interesting to use this as a way to implement something like [The Phantom Edit](https://en.wikipedia.org/wiki/The_Phantom_Edit) in a way which is legally redistributable.  Anyone who has the original movie and the `mcf` file can now view your remix.

**Comment by cellularmitosis** [comment]
example:

```
01:02:31.020 --> 01:02:49.800
george_lucas=idiot
```

**Comment by mwaclawek** [comment]
Definitely!

Thank you very much for this proposal!

We just have to find a name for this new category-to-be. Unlike all the other categories, `remix` is something neutral that can't really be "blocked".

My ideas would be (in that order) `dispensable`, `tediousness` or `idiocy`. What do you think?

We still have to find a proper parent category for that new category as well. Maybe even something new such as `art`.

**Comment by mwaclawek** [comment]
This has been implemented in https://github.com/delight-im/MovieContentFilter/commit/784e5a3bfe268e5a9dd769902017a88deec918ca

Thank you!
