### ISSUE TITLE
MCF format: Distinguishing between positive and negative presentations

### ISSUE THREAD

**Issue by luke-jr** [delight-im/MovieContentFilter#18]
There are likely cases where a user might want to filter positive presentations of things (eg, "good guys" doing something bad), but leave negative presentations (bad guys doing the same thing).

**Comment by ocram** [comment]
Thanks!

The good people being naked is better than the bad people, if you can’t stand nudity in movies? Or gruesome violence by good guys being preferable to the same violence by bad guys? Or whether swear words are bad depends on who utters them?

Not really sure here, as you can see, but perhaps you can give some better examples.

**Comment by luke-jr** [comment]
Nudity isn't a good example for this. But for example, it might be okay for bad guys to use racist language, but you don't want your children to see the good guys (whom they might imitate) doing the same.

**Comment by ocram** [comment]
That makes sense, thank you.

I agree, but I’m also pretty sure this way of filtering would be less popular compared to the current option of just blocking all such language, no matter by whom. So for reasons of scope and simplicity, and considering our priorities, we won’t implement this for now but perhaps revisit it later.
